blank_issues_enabled: true
contact_links:
  - name: GeoPandas Discussions
    url: https://github.com/geopandas/geopandas/discussions
    about: Ask a general question about GeoPandas (e.g., usage, installation)
